### ISSUE TITLE
Speed test

### ISSUE THREAD

**Issue by BenjaminHoegh** [xemlock/php-latex#8]
### Description

How is the speed of this compared to MathJax?

**Comment by xemlock** [comment]
Hi @BenjaminHoegh, 
I'm really sorry for late response.

The two can't really be compared, because they serve different purposes.

The main goal of php-latex library is tokenizing / parsing LaTeX markup and then re-rendering it as either:
* structurally valid LaTeX code (so that `pdflatex` always succeeds), or
* as a HTML equivalent of the LaTeX markup sans math mode support - which had to be rendered in the browser via a JS-based solution (such as MathJax)

So this lib can't be used as a substitute for MathJax, because it still needs the latter for rendering math formulas.

I hope my, rather evasive, response answers your question.
